### ISSUE TITLE
Normalize the heading size + section divisions for book

### ISSUE THREAD

**Issue by nniiicc** [HKDCWorkshop/HongKongCurationWorkshop#24]
Leafing through  - we've been somewhat non-standard when giving heading sizes (h1 + h2) to different content... 

We should
- agree on sizes, names (works cited vs. bibliography) and when / where to link out to existing pages
- edit each document to reflect those standards

**Comment by akthom** [comment]
Formatting on slides might need some finnessing too -- I've been wonky with bolding/underlines/etc.  This should be the next to last thing we focus on though

**Comment by nniiicc** [comment]
will open different issue for slides
